server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - AddRequestHeader=X-gateway, donghyeon.site # 먼저 적용됨
          routes:
            - id: test-route
              uri: https://httpbin.org
              predicates:
                - Path=/test/**
              filters:
                - StripPrefix=1 # 제거할 경로 세그먼트 개수

            - id: search
              uri: https://httpbin.org/anything
              predicates:
                - Path=/search/**
              #  GET /search 로 요청을 보내면 uri에 /anything이 있어도 /anything을 무시하고 도메인 루트로 리디렉션.
              #  StripPrefix를 활용하는 경우 /search/status 처럼 하위 경로가 있어야 /anything/status로 정상 라우팅
              #  Producation 환경에서는 일반적으로 uri에 추가적인 경로가 붙지 않기 때문에 사용할 필요는 없을 것 같음.
              filters:
                - RewritePath=/search(?<segment>/?.*), /anything$\{segment} # prefix 변경
                - AddResponseHeader=Cookie, chocolate
                - AddRequestHeader=X-gateway, api-gateway # 덮어쓰기가 아니라 추가됨

            - id: booking
              uri: https://httpbin.org
              predicates:
                - Path=/book/**
              filters:
                - StripPrefix=1

            - id: queue
              uri: https://httpbin.org
              predicates:
                - Path=/queue/**
              filters:
                - StripPrefix=1
                - RemoveRequestHeader=Cookie